# Generated by Django 6.0.3 on 2026-04-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body_region', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('legs', 'Legs')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('plyometrics', 'Plyometrics')], max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.equipment')),
                ('primary_muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_exercises', to='exercises.musclegroup')),
                ('secondary_muscle_groups', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
